### ISSUE TITLE
The revert of groupThree

### ISSUE THREAD

**Issue by LJKOJBK** [classfour/softwareEngineering#6]
The static page that I write before, which contained in "zytnb" folder, should be deleted, and it will be never used, so, why you reverted it and create a new branch? @xbyige

**Comment by xbyige** [comment]
fixed.

**Comment by xbyige** [comment]
and there have a folder named "zytnb" in group five, why?

**Comment by LJKOJBK** [comment]
Oh, maybe I pulled to groupFive branch before, and my team leader hasn't checked it clearly, sorry, that folder is useless now.
